PROJECT_BULK_UPSERT_URL = 'projects/bulk_upsert/'
PROJECT_ID_LIST_URL = 'projects/ids/'
TRACE_BULK_UPSERT_VERBOSE_URL = 'traces/bulk_upsert_verbose/'
TRACE_RECORD_BULK_UPSERT_URL = 'trace_records/bulk_upsert/'
TRACE_RECORD_BULK_INSERT_URL = 'trace_records/bulk_insert/'
TRACE_ID_LIST_URL = 'traces/ids/'
PROJECT_TRACE_MAPPING_BULK_UPSERT_VERBOSE_URL = 'project_trace_mappings/bulk_upsert_verbose/'
PROJECT_METADATA_BULK_UPSERT_URL = 'project_metadata/bulk_upsert/'